<div class="payment-types">
<img src="{{skin url="images/payments.png"}}" alt="we accept all major cards" title="we accept all major cards" />
</div>

<div class="social-media">
<ul>
  	<li>
    	<a target="_blank" href="http://www.facebook.com/xxxx"><img src="{{skin url="images/fb-24.png"}}" alt="become our fan on facebook" title="become our fan on facebook">Facebook</a>
    </li>
  	<li>
    	<a target="_blank" href="https://twitter.com/xxxx"><img src="{{skin url="images/twitter-24.png"}}" alt="follow us on twitter" title="follow us on twitter">Twitter</a>
   	</li>
 	<li>
		<link href="https://plus.google.com/xxxx" rel="publisher" />
		<a target="_blank" href="https://plus.google.com/xxxx?prsrc=3" style="text-decoration:none;"><img src="https://ssl.gstatic.com/images/icons/gplus-32.png" alt="" style="border:0;width:24px;height:24px;"/>Google+</a>
		<script type="text/javascript">gapi.plus.go();</script>
  	</li>
</ul>
</div>