<div class="box informational">
  	<div class="col-md-3 col-sm-3 footer-block">
  		<h4>About</h4>
    	<ul>
      		<li class="stemap"><a href="{{store direct_url="catalog/seo_sitemap/category"}}">Sitemap</a></li>
      		<li><a href="{{store direct_url="about-us"}}">About Us</a></li>
      		<li><a href="{{store direct_url="contacts"}}">Contact Us</a></li>
    		<li class="last privacy"><a href="{{store direct_url="privacy-policy"}}">Privacy Policy</a></li>
		</ul>
	</div>
	<div class="col-md-3 col-sm-3 footer-block">
		<h4>Information for you</h4>
    	<ul>     
      		<li><a href="{{store direct_url="faqs"}}">FAQs</a></li>
      		<li><a href="{{store direct_url="delivery"}}">Delivery</a></li>
      		<li><a href="{{store direct_url="blog"}}">Our Blog</a></li>
    		<li class="last privacy"><a href="{{store direct_url="privacy-policy"}}">Privacy Policy</a></li>
		</ul>
	</div>
	<div class="col-md-3 col-sm-3 footer-block">
		<h4>Your Peace of Mind</h4>
    	<ul>
      		<li><a href="{{store direct_url="sales/guest/form"}}">My Order</a></li>
      		<li><a href="{{store direct_url="privacy-policy"}}">Privacy Policy</a></li>
      		<li><a href="{{store direct_url="terms-and-conditions"}}">Terms & Conditions</a></li>
    		<li class="last privacy"><a href="{{store direct_url="privacy-policy"}}">Privacy Policy</a></li>
		</ul>
	</div>
	<div class="col-md-3 col-sm-3 footer-block">
		<div class="footer-contact">
			<h4>Business Information</h4>
	    	<ul>
	      		<li>ProductiveMinds Ltd</li>
	      		<li><strong>Registered Office</strong></li>
	      		<li>Unit xx</li>
	      		<li>Dove Bisness Centre</li>
	      		<li>East Sussex, BN2 8AA</li>
	      		<li>United Kingdom</li>
			</ul>
		</div>
	</div>
</div>