<ul class="bxslider">
<li>
  	<a href="{{store url="shopnow/new"}}">
  		<img src="{{skin url="images/hero/prominds1.png"}}" title="Shop from our latest collection"  />
  	</a>
</li>
<li>
	<a href="{{store url="shopnow/specialoffers"}}">
		<img src="{{skin url="images/hero/prominds2.jpg"}}" title="Special offers for you" />
		</a>
</li>
<li>
	<a href="{{store url=""}}">
		<img src="{{skin url="images/hero/prominds3.png"}}" title="Welcome to our shop" />
	</a>
</li>
</ul>

<script type="text/javascript">  
	jQuery(document).ready(function() {
  		jQuery('.bxslider').bxSlider({
  			mode: 'fade',
  			captions: true,
  			responsive: true,
			auto: true
		});
	});
</script>